"""Add report_json to scans

Revision ID: 21c4edd80579
Revises: 9ecf69bf6a3b
Create Date: 2026-08-01 21:10:37.078488

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '21c4edd80579'
down_revision = '9ecf69bf6a3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_json', sa.JSON(), nullable=True))
        batch_op.drop_column('headers_json')
        batch_op.drop_column('ssl_valid')
        batch_op.drop_column('cms_name')
        batch_op.drop_column('findings_json')
        batch_op.drop_column('remediation_json')
        batch_op.drop_column('ssl_expiry')
        batch_op.drop_column('cms_version')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cms_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ssl_expiry', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('remediation_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('findings_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cms_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ssl_valid', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('headers_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_column('report_json')

    # ### end Alembic commands ###
