"""Initial scan model

Revision ID: 9ecf69bf6a3b
Revises: 
Create Date: 2026-07-31 01:49:33.814839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ecf69bf6a3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_url', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=5), nullable=False),
    sa.Column('ssl_valid', sa.Boolean(), nullable=False),
    sa.Column('ssl_expiry', sa.String(length=100), nullable=True),
    sa.Column('cms_name', sa.String(length=100), nullable=True),
    sa.Column('cms_version', sa.String(length=50), nullable=True),
    sa.Column('headers_json', sa.JSON(), nullable=True),
    sa.Column('findings_json', sa.JSON(), nullable=True),
    sa.Column('remediation_json', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scans')
    # ### end Alembic commands ###
